version: '3'

tasks:
  setup:
    desc: Installs all external dependencies
    deps: [install:gotest, install:air]

  default:
    - task: run

  build:
    desc: Build the go binary
    dir: build
    cmds:
      - go build -v ../.

  run:
    desc: Run go program
    env:
      ENV: local
    cmds:
      - wire
      - sleep 1 || timeout /t 1; air

  install:gotest: go install github.com/rakyll/gotest@latest
  install:air: go install github.com/cosmtrek/air@latest
