version: '3'

tasks:
  setup:
    desc: Installs all external dependencies
    deps: [install:air]

  default:
    - task: run

  build:
    desc: Build the go binary
    dir: build
    cmds:
      - go build -v ../.

  run:
    desc: Run go program
    env:
      ENV: local
    cmds:
      - air

  install:air: go install github.com/cosmtrek/air@latest
